version: 2
updates:
  - package-ecosystem: npm
    directory: "/keo-app"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/keo-be"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
